/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author Dev. Aníbal Henrique
 */
public class FinishPage extends javax.swing.JFrame {
static FinishPage finishFrame = new FinishPage();
    /**
     * Creates new form FinishPage
     */
    public FinishPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFinish = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnProximo = new javax.swing.JButton();
        btnHidden = new javax.swing.JButton();
        jPainel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxBarcaDesktop = new javax.swing.JCheckBox();
        boxBarcaCLI = new javax.swing.JCheckBox();
        boxBarcaWebCloud = new javax.swing.JCheckBox();
        labelInstall = new javax.swing.JLabel();
        labelTranslate = new javax.swing.JLabel();
        textFieldPath = new javax.swing.JTextField();
        btnPath = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtSerialKey = new javax.swing.JTextField();
        labelSerialKey = new javax.swing.JLabel();
        titleSerialKey = new javax.swing.JLabel();
        titleSerialKeyMaster = new javax.swing.JLabel();
        checkBoxLastVersionsOn = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        txtTitleTermsAndLicense = new javax.swing.JLabel();
        txtSubtitleTermsAndLicense = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 1, 1));
        setMinimumSize(new java.awt.Dimension(710, 520));
        setPreferredSize(new java.awt.Dimension(710, 520));
        getContentPane().setLayout(null);

        btnFinish.setText("concluido");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinish);
        btnFinish.setBounds(545, 487, 83, 22);
        getContentPane().add(filler1);
        filler1.setBounds(628, 417, 0, 0);

        btnProximo.setText("proximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProximo);
        btnProximo.setBounds(452, 487, 75, 22);

        btnHidden.setText("hidden");
        btnHidden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHiddenActionPerformed(evt);
            }
        });
        getContentPane().add(btnHidden);
        btnHidden.setBounds(339, 487, 72, 22);

        jPainel.setBackground(new java.awt.Color(51, 51, 51));
        jPainel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dev. Aníbal Henrique\\OneDrive\\Imagens\\barca-logo.jpeg")); // NOI18N

        boxBarcaDesktop.setBackground(new java.awt.Color(1, 1, 1));
        boxBarcaDesktop.setForeground(new java.awt.Color(204, 204, 204));
        boxBarcaDesktop.setText("Barca Desktop");
        boxBarcaDesktop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBarcaDesktopActionPerformed(evt);
            }
        });

        boxBarcaCLI.setBackground(new java.awt.Color(1, 1, 1));
        boxBarcaCLI.setForeground(new java.awt.Color(204, 204, 204));
        boxBarcaCLI.setText("Barca CLI");

        boxBarcaWebCloud.setBackground(new java.awt.Color(1, 1, 1));
        boxBarcaWebCloud.setForeground(new java.awt.Color(204, 204, 204));
        boxBarcaWebCloud.setText("BWC Barca Web Cloud");
        boxBarcaWebCloud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBarcaWebCloudActionPerformed(evt);
            }
        });

        labelInstall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelInstall.setForeground(new java.awt.Color(204, 204, 204));
        labelInstall.setText("Selecione o que deseja instalar/atualizar");

        labelTranslate.setForeground(new java.awt.Color(204, 204, 204));
        labelTranslate.setText("v1.0.0");

        textFieldPath.setBackground(new java.awt.Color(204, 204, 204));
        textFieldPath.setForeground(new java.awt.Color(51, 51, 51));
        textFieldPath.setText("C:\\Program Files (x86)\\Barca");

        btnPath.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPath.setText("Alterar");
        btnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(textFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxBarcaWebCloud, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxBarcaDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxBarcaCLI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelInstall, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelInstall, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(boxBarcaCLI)
                        .addGap(18, 18, 18)
                        .addComponent(boxBarcaWebCloud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxBarcaDesktop))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPainel.add(jPanel1, "card2");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelSerialKey.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelSerialKey.setForeground(new java.awt.Color(204, 204, 204));
        labelSerialKey.setText("Serial Key");

        titleSerialKey.setForeground(new java.awt.Color(204, 204, 204));
        titleSerialKey.setText("Este programa tem privilégios em categorias de usuários, no modo básico você tem gratuito uma chave.");

        titleSerialKeyMaster.setForeground(new java.awt.Color(204, 204, 204));
        titleSerialKeyMaster.setText("Para utilizar todos recursos do ecossistema Barca, você vai precisar de uma chave como serial. ");

        checkBoxLastVersionsOn.setBackground(new java.awt.Color(51, 51, 51));
        checkBoxLastVersionsOn.setForeground(new java.awt.Color(204, 204, 204));
        checkBoxLastVersionsOn.setText("Deseja instalar as últimas versões das ferramentas?");
        checkBoxLastVersionsOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxLastVersionsOnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleSerialKey)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(titleSerialKeyMaster)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(checkBoxLastVersionsOn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(labelSerialKey)
                .addGap(28, 28, 28)
                .addComponent(txtSerialKey, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleSerialKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSerialKeyMaster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSerialKey))
                .addGap(69, 69, 69)
                .addComponent(checkBoxLastVersionsOn)
                .addGap(58, 58, 58))
        );

        jPainel.add(jPanel3, "card2");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTitleTermsAndLicense.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTitleTermsAndLicense.setText("License Agreement");

        txtSubtitleTermsAndLicense.setText("Por favor leia os termos de licença antes de instalar Barca 64-bit.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitleTermsAndLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtSubtitleTermsAndLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitleTermsAndLicense)
                .addGap(10, 10, 10)
                .addComponent(txtSubtitleTermsAndLicense)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jPainel.add(jPanel2, "card2");

        getContentPane().add(jPainel);
        jPainel.setBounds(-10, 90, 716, 346);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        // remover painel
        jPainel.removeAll();
        jPainel.repaint();
        jPainel.revalidate();
        
        // adicionar painel
        jPainel.add(jPanel1);
        jPainel.repaint();
        jPainel.revalidate();
        
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnHiddenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHiddenActionPerformed
        // TODO add your handling code here:
        
        // remover painel
        jPainel.removeAll();
        jPainel.repaint();
        jPainel.revalidate();
        
        // adicionar painel
        jPainel.add(jPanel3);
        jPainel.repaint();
        jPainel.revalidate();
    }//GEN-LAST:event_btnHiddenActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // TODO add your handling code here:
        // remover painel
        jPainel.removeAll();
        jPainel.repaint();
        jPainel.revalidate();
        
        // adicionar painel
        jPainel.add(jPanel2);
        jPainel.repaint();
        jPainel.revalidate();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void checkBoxLastVersionsOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxLastVersionsOnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxLastVersionsOnActionPerformed

    private void boxBarcaWebCloudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBarcaWebCloudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxBarcaWebCloudActionPerformed

    private void btnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPathActionPerformed

    private void boxBarcaDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBarcaDesktopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxBarcaDesktopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinishPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinishPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinishPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinishPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinishPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxBarcaCLI;
    private javax.swing.JCheckBox boxBarcaDesktop;
    private javax.swing.JCheckBox boxBarcaWebCloud;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnHidden;
    private javax.swing.JButton btnPath;
    private javax.swing.JButton btnProximo;
    private javax.swing.JCheckBox checkBoxLastVersionsOn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPainel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelInstall;
    private javax.swing.JLabel labelSerialKey;
    private javax.swing.JLabel labelTranslate;
    private javax.swing.JTextField textFieldPath;
    private javax.swing.JLabel titleSerialKey;
    private javax.swing.JLabel titleSerialKeyMaster;
    private javax.swing.JTextField txtSerialKey;
    private javax.swing.JLabel txtSubtitleTermsAndLicense;
    private javax.swing.JLabel txtTitleTermsAndLicense;
    // End of variables declaration//GEN-END:variables
}
