/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author Dev. Aníbal Henrique
 */
public class TermsAndLicenses extends javax.swing.JFrame {

    /**
     * Creates new form TermsAndLicenses
     */
    public TermsAndLicenses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBarcaInstaller = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnBackTermsAndLicense = new javax.swing.JButton();
        btnCancelarTermsAndLicense = new javax.swing.JButton();
        btnNextTermsAndLicense = new javax.swing.JButton();
        txtTitleTermsAndLicense = new javax.swing.JLabel();
        txtSubtitleTermsAndLicense = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Barca 1.0  64-bit Setup");
        setMaximumSize(new java.awt.Dimension(710, 475));
        setMinimumSize(new java.awt.Dimension(710, 475));
        setPreferredSize(new java.awt.Dimension(710, 475));
        getContentPane().setLayout(null);

        txtBarcaInstaller.setText("Barca © Installer");
        getContentPane().add(txtBarcaInstaller);
        txtBarcaInstaller.setBounds(20, 350, 100, 16);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(120, 360, 550, 10);

        btnBackTermsAndLicense.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBackTermsAndLicense.setText("< Voltar");
        btnBackTermsAndLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTermsAndLicenseActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackTermsAndLicense);
        btnBackTermsAndLicense.setBounds(340, 390, 90, 30);

        btnCancelarTermsAndLicense.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarTermsAndLicense.setText("Cancelar");
        btnCancelarTermsAndLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTermsAndLicenseActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarTermsAndLicense);
        btnCancelarTermsAndLicense.setBounds(590, 390, 90, 30);

        btnNextTermsAndLicense.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNextTermsAndLicense.setText("Avancar");
        btnNextTermsAndLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextTermsAndLicenseActionPerformed(evt);
            }
        });
        getContentPane().add(btnNextTermsAndLicense);
        btnNextTermsAndLicense.setBounds(440, 390, 90, 30);

        txtTitleTermsAndLicense.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTitleTermsAndLicense.setText("License Agreement");
        getContentPane().add(txtTitleTermsAndLicense);
        txtTitleTermsAndLicense.setBounds(30, 30, 130, 20);

        txtSubtitleTermsAndLicense.setText("Por favor leia os termos de licença antes de instalar Barca 64-bit.");
        getContentPane().add(txtSubtitleTermsAndLicense);
        txtSubtitleTermsAndLicense.setBounds(40, 60, 410, 16);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 103, 690, 0);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 110, 690, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextTermsAndLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextTermsAndLicenseActionPerformed
        // TODO add your handling code here:
        SerialKey jframe = new SerialKey();
        jframe.setVisible(true);
        jframe.setDefaultCloseOperation(SerialKey.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnNextTermsAndLicenseActionPerformed

    private void btnCancelarTermsAndLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTermsAndLicenseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarTermsAndLicenseActionPerformed

    private void btnBackTermsAndLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTermsAndLicenseActionPerformed
        // TODO add your handling code here:
        IntroPage jframe = new IntroPage();
        jframe.setVisible(true);
        jframe.setDefaultCloseOperation(IntroPage.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnBackTermsAndLicenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TermsAndLicenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TermsAndLicenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TermsAndLicenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TermsAndLicenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TermsAndLicenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackTermsAndLicense;
    private javax.swing.JButton btnCancelarTermsAndLicense;
    private javax.swing.JButton btnNextTermsAndLicense;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txtBarcaInstaller;
    private javax.swing.JLabel txtSubtitleTermsAndLicense;
    private javax.swing.JLabel txtTitleTermsAndLicense;
    // End of variables declaration//GEN-END:variables
}
